#!/usr/bin/env bash
# Git subdomains

get_domain () {
	record=$(dig $1 | awk '/ANSWER SECTION/ {getline; print $4}')
	ip=$(dig $1 | awk '/ANSWER SECTION/ {getline; print $5}')
	sub=$(echo "$1" | cut -d "." -f1)
	echo "The subdomain $sub is a $record record and points to $ip"
}
if [ -z "$2" ]; then
	for i in 'www' 'lb-01' 'web-01' 'web-02'; do
		sub=$i.$1
		get_domain "$sub"
	done
else
	sub=$2.$1
	get_domain "$sub"
fi
