#!/usr/bin/env bash
# This script transfers a file from our client to a server
if [ -z "$3" ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit
fi
scp $1 $3@$2:~/ -i $4
