#!/usr/bin/env bash
# This script transfers a file from our client to a server
if [ -z "$3" ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit
else if [ -z "$4" ]
then
	scp "$1" "$3@$2:~/"
else
	scp -i "$4" "$1" "$3@$2:~/"
fi
