#!/usr/bin/env bash
# This script insatall nginx into the server
sudo apt-get -y update
sudo ap-get -y install nginx
sudo chown -R $USER:$USER /var/www/html
sudo chmod -R 755 /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx start
