#!/usr/bin/env bash
# This script Configure your Nginx server so that /redirect_me is redirecting to another page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'nginx HTTP'
echo -e 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo sed -i '24i\        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
