#!/usr/bin/env bash
# This script insatall nginx into the server

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sed -ie "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 301;/" /etc/nginx/sites-available/default
sudo service nginx start
