#!/usr/bin/env bash
# This script Configure your Nginx server so that /redirect_me is redirecting to another page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'nginx HTTP'
echo -e 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo sed -i '24i\        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo chmod -R 755 /usr/share/nginx/html
echo -e "Ceci n'est pas une page" > /usr/share/nginx/html/custom_50x.html
sudo sed -i "25i/	error_page 404 /custom_404.html location = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}" /etc/nginx/sites-available/default
sudo service nginx restart
