#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.
sudo -y apt-get update

sudo apt-get -y install haproxy=2.8.\*

echo "
frontend http
	bind *:80
	mode http
	default_backend web-server

backend web-server
	balance roundrobin
	server web-01 54.90.27.152:80 check
	server web-02 35.153.17.86:80 check
" >> /etc/haproxy/haproxy.cfg

echo "ENABLED=1" >> /etc/default/haproxy

sudo service haproxy restart
