#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.
# shellcheck disable=SC2028
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8
sudo -y apt-get install haproxy=2.8.\*

echo 'frontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-server\n\nbackend web-server\n\tbalance roundrobin\n\tserver web-01 54.90.27.152:80 check\n\tserver web-02 35.153.17.86:80 check' >> /etc/haproxy/haproxy.cfg 
sudo service haproxy start
