#!/usr/bin/env bash
# running Nginx and make it listening on port 80 of all the server’s active IPv4 IPs
rm -f /etc/nginx/sites-enabled/default
cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
