#!/usr/bin/env bash
# this script manages manage_my_process script
if [$1 -eq "start"];
then
	./manage_my_process &
	echo "$$" > my_process.pid
	echo "manage_my_process started"
elif [$1 -eq "stop"];
then
	pkill -f manage_my_process
	rm my_process.pid
	echo "manage_my_process stopped"
elif [ $1 -eq "restart" ];
then
	pkill -f manage_my_process
        rm my_process.pid
	./manage_my_process &
        echo "$$" > my_process.pid
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
