#!/usr/bin/env bash
# this script displays To infinity and beyond indefinitely
x=$(pgrep -nf 100-process_and_pid_file)
echo "$x" > /var/run/myscript.pid
function trap_term()
{
	echo "I hate the kill command"
	rm /var/run/myscript.pid
	exit
}
function trap_int()
{
	echo "Y U no love me?!"
	rm /var/run/myscript.pid
	exit
}
trap trap_term  SIGTERM
trap trap_int SIGINT
while true;
do
	echo "To infinity and beyond"
	sleep 2
done
