#!/usr/bin/env bash
# this script manages manage_my_process script
if [ "$1" = "start" ];
then
	./manage_my_process &
	echo "$$" > /var/run/my_process.pid
	echo "manage_my_process started"
elif [ "$1" = "stop" ];
then
	sudo rm /var/run/my_process.pid
	pkill -f ./manage_my_process \
	&& echo "manage_my_process stopped" &

elif [ "$1" = "restart" ];
then
	disown -r
        rm /var/run/my_process.pid
	./manage_my_process &
        echo "$$" > /var/run/my_process.pid
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
