#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd.
file=$"/etc/passwd"
IFS=":"
while read -r -a array;
do
	echo "The user ${array[0]} is part of the ${array[2]} gang, lives in ${array[5]} and rides ${array[6]}. ${array[3]}'s place is protected by the passcode ${array[1]}, more info about the user here: ${array[4]}"
done<$file
