#!/usr/bin/env bash
# gives you information about the school file

if [ -e "school" ]
then
	echo "school file exists"
else
	echo "school file does not exist"
	exit
fi

if [ -s "school" ]
then
	echo "school file is not empty"
else
	echo "school file is empty"
fi

if [ -f "school" ]
then
	echo "school is a regular file"
fi
