#!/usr/bin/env bash
# this script change the ip of localhost and facebook.com
cp /etc/hosts ~/hosts.new
sed -ie 's/127.*$/127.0.0.2 localhost/' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
