#!/usr/bin/env bash
# this script change the ip of localhost and facebook.com
cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1( |\t){1,10}localhost( |\t){0,10}$/^127.0.0.2( |\t){1,10}localhost( |\t){0,10}$/ hosts.new
echo "8.8.8.8 facebook.com"  hosts.new
cp -f ~/hosts.new /etc/hosts
