#!/usr/bin/env bash
# Running Nginx as the nginx user.
sed -i '1i\user nginx;' /etc/nginx/nginx1.conf
sed -i 's/80/8080 /' /etc/nginx/sites-enabled/default
pkill apache2
service nginx stop
sudo -unginx service nginx start
